WaterWorks/WaterWorks/Models/ErrorViewModel.cs
using System;

namespace WaterWorks.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WaterWorks/WaterWorks/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace WaterWorks.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ManagementCommittee()
        {
            return View();
        }
    }
}

WaterWorks/WaterWorks/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace WaterWorks.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WaterWorks/WaterWorks/Controllers/DonateController.cs
using Microsoft.AspNetCore.Mvc;

namespace WaterWorks.Controllers
{
    public class DonateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WaterWorks/WaterWorks/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WaterWorks.Models;

namespace WaterWorks.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WaterWorks/WaterWorks/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WaterWorks.Controllers
{
    public class ProjectsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WaterWorks/WaterWorks/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WaterWorks.Controllers
{
    public class ReportsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WaterWorks/WaterWorks/Controllers/WaterPumpsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WaterWorks.Controllers
{
    public class WaterPumpsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Alinafe()
        {
            return View();
        }

        public IActionResult RopePump()
        {
            return View();
        }
    }
}

WaterWorks/WaterWorks/Views/About/Index.cshtml
@{
    ViewData["Title"] = "About";
}

<p>Water Works is a charity committed to assisting communities gain access to safe drinking water and hygienic sanitation facilities. Our approach is not to give hand outs, but to empower people to meet their own needs.</p>

<h1 style="text-align:center">The Malawi Water Team</h1>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/Kingston-Tsamba.jpg" alt="Kingston Tsama" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Kingston Tsamba (Senior Builder)</span></p>
        <p>Kingston is one of the newer members to Water Works. With his strong work ethic, his sharp organisational skills and a good command of English, he leads his construction crew with latrine construction.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/Maxwell.jpg" alt="Maxwell Khombe" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Maxwell Khombe (Senior Water Point Technician)</span></p>
        <p>Maxwell is a very smart and engaging team member. He leads the installation of the pumps and trains the village water committee on how to install and maintain the pumps. Maxwell is trained on not only Water Works’ pumps, but also the Afridev and Malda pumps, and has led training sessions to pump technicians of other NGOs.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/Black.jpg" alt="Mr Black talking to villagers" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Black Chakumodzi (Team Leader)</span></p>
        <p>Mr Black has spent much of his life mobilising communities to build their own toilets and advising on the importance of good hygiene practices.</p>
        <p>Mr Black is the Water Works team leader and ensures that the projects are community led. He excels when engaging and promoting partnerships with communities.</p>
    </div>
</div>

<h1 style="text-align:center">The Management Team</h1>

<div class="profile">
    <div class="profile-picture">
        <!--img src="~/images/HOME-PAGE-1.jpg" alt="Simon." width="299" height="206" style="float:left; margin-bottom: 5px; margin-top: 30px; margin-right: 20px;" title="" /-->
        <video width="300" controls=controls preload="auto">
            <source src="~/videos/HomePageVideo.mp4" type="video/mp4" />
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="profile-text">
        <p><span class="header">Simon Cohen (Director)</span></p>
        <p>Simon founded the charity in September 2008 in response to the lack of sustainable water points in sub-Saharan Africa. With Master’s degrees in Civil and Environmental Engineering and Development Studies, Simon is able to help guide the development of Water Work’s water pumps, programmes and strategy. He excels when engaging communities, building partnerships and providing training. When not working for Water Works, Simon consults for other water NGOs in various countries including Angola, the Sudan and Mozambique.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/PeterPhiri.jpg" alt="Peter" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Peter Phiri (Programme Manager)</span></p>
        <p>Peter has spent much of his professional life working in a project management role and has worked on a range of development projects and programmes covering rural and urban WASH, infrastructure development covering transport and irrigation and labour-intensive community development programmes. He has more than 12 years’ work experience on European Development Fund (EDF) financed projects in Malawi among others. He is therefore conversant with international development procurement and contract management procedures and has demonstrable experience in mainstreaming, monitoring and evaluating cross-cutting issues such as gender, environment, HIV and AIDS is development projects.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/Jeff.jpg" alt="Jeff" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Jeff Cohen (Business Development Manager)</span></p>
        <p>Jeff‘s involvement with Water Works began when he took responsibility for fund raising. He has substantial experience in raising money for various voluntary groups. His career has been in the field of mental health and human rights, but is now taking a more active role in the management of Water Works. He helped to manage the programme in Malawi in 2013-2014 and is now fully in charge of Water Works’ Business Development.</p>
    </div>
</div>

<div style="text-align:center;font-size:20px">
    Read about the <a asp-area="" asp-controller="About" asp-action="ManagementCommittee">Water Works Management Committee</a>
</div>

WaterWorks/WaterWorks/Views/About/ManagementCommittee.cshtml
@{
    ViewData["Title"] = "About";
}

<h1 style="text-align:center">Water Works Management Committee</h1>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/Suzanna.jpg" alt="Suzanna" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Suzanna van Schaick (Chair)</span></p>
        <p>Suzanna has extensive clinical experience as a doctor, varied educational and teaching experience and insights from recent Voluntary Service Overseas. She has:</p>
        <ul>
            <li>over 30 years experience in general practice in the UK, 6 months in hospital Accident & Emergency in 2001-2</li>
            <li>20 years experience writing & producing medical educational materials, using multiple media for varied audiences</li>
            <li>2 years (08-10) working to help improve health knowledge and practice in rural Cambodia, including very varied teaching and training with an interpreter in a low resource environment</li>
        </ul>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/MikeWilkins.jpg" alt="Mike Wilkins" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Mike Wilkins (Treasurer)</span></p>
        <p>Mike has worked in the textile, food and drink industries and as a social worker and manager for 13 years. Later he worked as a director with the two UK charities and as a grant-maker with the National Lottery Charities Board, the Big Lottery Fund and Awards for All. His most recent post was with Capacity Builders, a Cabinet Office agency responsible for funding and developing infrastructure support for the voluntary and community sector. Mike is currently the lay vice chair of the NHS Nottingham North and East Clinical Commissioning Group with responsibility for patient and public engagement.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/MichaelLee.jpg" alt="Ayari" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Michael Lee (Committee Member)</span></p>
        <p>After a long career in social care, Mike took early retirement at the end of 2010. His specialism was in research, evaluation and data processing, although his last job as one of the Heads of Service in the Children's Department of Nottinghamshire County Council also encompassed communications. He is particularly concerned that in the 21st Century there is still a need to develop the provision of a basic utility like clean water in certain parts of the world - hence his wholehearted support for the aims of Water Works.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/linda.jpg" alt="Linda doing survey" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Linda Chisale (Committee Member)</span></p>
        <p>Linda is from Lilongwe and worked for Water Works as project assistant and community mobiliser. She is a great communicator and helped to provide the link between the project management and the villages. She is now living in San Francisco, studying Hotel, Restaurant and Institutional Management.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/IanSmout.jpg" alt="Ian Smout" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Ian Smout (Committee Member)</span></p>
        <p>Ian is a chartered civil engineer and was pleased to join the Water Works Management Committee in 2018, when he retired after more than 40 years working on water engineering and management in developing countries. He started his career working for an international consultancy company and then joined Loughborough University in 1987. In addition, he has been a trustee of a disaster relief charity since 2008.</p>
    </div>
</div>

<div class="profile">
    <div class="profile-picture">
        <img src="~/images/Tim.jpg" alt="Tim" title="" />
    </div>
    <div class="profile-text">
        <p><span class="header">Tim Bell (Former Chair)</span></p>
        <p>It is with immense sadness that we have to announce that Tim Bell died in September 2018. Tim stepped down from his position as Chair at the AGM in June, owing to uncertainty because of his illness. He remained committed to Water Works and even nominated us as one of two charities he wanted friends and family to support in his memory.</p>
    </div>
</div>

<p>The Management Committee would also like to pay tribute to Ben Cohen, who designed and maintained this website. Tragically he died in November. We would like to thank his close friend, Martin Tasker for updating the site. </p>

<div style="text-align:center;font-size:20px">
    <br />
    Read about the <a asp-area="" asp-controller="About" asp-action="">Water Works Malawian and Management Team</a>
</div>

WaterWorks/WaterWorks/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div style="text-align:center">
    <br /><br />
    <p>
        General Enquires: <a href="mailto:contact@waterworkscharity.org">contact@waterworkscharity.org</a>

        <br />     <br />     <br />

        Business Development Manager: <a href="mailto:jeffrey.cohen@waterworkscharity.org">jeffrey.cohen@waterworkscharity.org</a>

        <br />     <br />     <br />

        Director: <a href="mailto:simon.cohen@waterworkscharity.org">simon.cohen@waterworkscharity.org</a>

        <br />     <br />     <br />

        Please visit us on our <a href="https://www.facebook.com/WaterWorksCharity/" target="_blank">facebook page</a>

        <br />     <br />     <br />
    </p>
</div>

WaterWorks/WaterWorks/Views/Donate/Index.cshtml
@{
    ViewData["Title"] = "Donate";
}

<div style="text-align:center;">We are a small organisation with very low running costs; more than 98% of the money that we receive is spent on our projects.</div>

<table class="news">
    <tr>
        <td>
            <a href="http://uk.virginmoneygiving.com/charity-web/charity/finalCharityHomepage.action?charityId=1005062" target="_blank" style="color:#666666">
                <h3>Give a single or monthly donation</h3>
                <img src="~/images/DonateSingleOrMonthly.jpg" alt="Donation." style="width:430px; height:275px" title="" />
            </a>

        </td>
        <td>
            <a href="http://uk.virginmoneygiving.com/charity-web/charity/finalCharityHomepage.action?charityId=1005062" target="_blank" style="color:#666666">
                <h3>Fundraise for us</h3>
                <img src="~/images/Fundraise.jpg" alt="Donation." style="width:430px; height:275px" title="" />
            </a>
        </td>
    </tr>
</table>

<br />
<div style="text-align:center">
    <a href="https://www.giveasyoulive.com/donate?cid=29738&wl=1&br=5#1" target="_blank" style="color:#666666">
        <h3>Give a gift</h3>
    </a>
</div>

Give a gift that makes a difference and receive personalised certificates and photographs. 100% of the donation goes towards, and is enough, to cover the cost of the construction materials.

<table class="news">
    <tr>
        <td style="width:33%">
            <a href="https://www.giveasyoulive.com/donate?cid=29738&wl=1&br=5#1" target="_blank" style="color:#666666">
                <h4>Family Latrine £12</h4>
                <img src="~/images/DonateLatrine.jpg" alt="Donate a latrine." title="" />
            </a>
            <div>
                <br />
                Give a vulnerable family a latrine for £12 and receive a personalised certificate.
            </div>
        </td>
        <td style="width:33%">
            <a href="https://www.giveasyoulive.com/donate?cid=29738&wl=1&br=5#1" target="_blank" style="color:#666666">
                <h4>Water Pump £70</h4>
                <img src="~/images/DonateWaterPump.jpg" alt="Donate a water pump." title="" />
            </a>
            <div>
                <br />
                Buy a water pump for a village for £70 and receive a personalised certificate on donation and personalised photograph when installed.
            </div>
        </td>
        <td style="width:33%">
            <a href="https://www.giveasyoulive.com/donate?cid=29738&wl=1&br=5#1" target="_blank" style="color:#666666">
                <h4>Support Entire Village £500</h4>
                <img src="~/images/DonateVillage.jpg" alt="Support village." title="" />
            </a>
            <div>
                <br />
                Support an entire village with latrines and a well for £500 and receive a personalised certificate on donation and personalised photo book upon completion.
            </div>
        </td>
    </tr>
</table>

WaterWorks/WaterWorks/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="homePageCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
    <ol class="carousel-indicators">
        <li data-target="#homePageCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#homePageCarousel" data-slide-to="1"></li>
        <li data-target="#homePageCarousel" data-slide-to="2"></li>
        <li data-target="#homePageCarousel" data-slide-to="3"></li>
        <li data-target="#homePageCarousel" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/HomePageHygiene.jpg" alt="Supporting communites with hygiene awareness programs." class="img-responsive" />
        </div>
        <div class="item">
            <img src="~/images/HomePageLatrines.jpg" alt="Assisting vulnerable families to build latrines." class="img-responsive" />
        </div>
        <div class="item">
            <img src="~/images/HomePageHandwashing.jpg" alt="Ensuring good hand washing practices." class="img-responsive" />
        </div>
        <div class="item">
            <img src="~/images/HomePageEmpowering.jpg" alt="Empowering people to meet their own needs." class="img-responsive" />
        </div>
        <div class="item">
            <img src="~/images/HomePageWater.jpg" alt="Supporting communities with safe drinking water." class="img-responsive" />
        </div>
    </div>
    <a class="left carousel-control" href="#homePageCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#homePageCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="section">
    Water Works is a grassroots charity committed to supporting rural Malawian communities gain access to <h2 style="display:inline;color:#0073e6">safe drinking water</h2> and <h2 style="display:inline;color:#0073e6">hygienic sanitation facilities</h2>. Our approach is not to give hand outs, but to empower people to meet their own  water, sanitation and hygiene needs. We do this by running <h2 style="display:inline;color:#0073e6">hygiene awareness programmes</h2>, providing technical assistance for latrine construction and training communities to install, manage and maintain one of our simple, innovative and sustainable <a asp-area="" asp-controller="WaterPumps" asp-action="">water pumps</a>.
</div>
<div class="section">
    <b>Privacy Notice</b>
    <ul>
        <li>If you have expressed an interest in Water Works by contacting this site (whether for information or a 'buy a gift' donation) we may use your email address to send you information about our activities as a charity, including major fundraising exercises.</li>
        <li>We will not share your data with anyone else (unless legally obliged to do so, e.g. in a police investigation).</li>
        <li>If you do not wish to be contacted in this way you can tell us at any time by emailing <a href="mailto:contact@waterworkscharity.org">contact@waterworkscharity.org</a> and we will delete your data from our records.</li>
        <li>If we have had no further contact from you after a period of 3 years we will delete your data from our records.</li>
    </ul>
</div>

WaterWorks/WaterWorks/Views/Projects/Index.cshtml
@{
    ViewData["Title"] = "Projects";
}

<div>

</div>
<p>
    Since 2009, we have assisted 94 Malawian villages to construct and maintain water points, providing safe drinking water for 17,000 people; supported 3,600 families to build hygienic latrines; helped a primary school with 300 students to build two blocks of latrines; and run hygiene awareness sessions for 5,400 people. Our household surveys have found that the projects have helped to dramatically reduce the percentage of children under five suffering from diarrhoea in the previous 2 weeks from 14.5% to 4%.
</p>

<p>
    Water Works focuses its programme in the Traditional Authority of Malili, south west of Malawi’s capital city Lilongwe. The area receives little assistance from the government or other NGOs despite, prior to our intervention, over half of the villages not having access to safe drinking water and most households not having a latrine.
</p>

<p>
    Our approach is not to give hand outs, but to empower people to meet their water, sanitation and hygiene needs. We do this by:
</p>

<ul>
    <li>
        promoting improved hygiene awareness and practice
    </li>
    <li>
        assisting the communities to install, manage and maintain one of our simple, innovative and sustainable water pump technologies
    </li>
    <li>
        supporting vulnerable households to construct latrines and hand-washing systems

    </li>
</ul>

<p>
    The hygiene awareness programme, which is led by our Malawian partner organisations, helps the communities to identify how their water, sanitation and hygiene practices may be impacting on their health. The communities develop action plans to address the issues, which would include the construction of latrines, the protection of water sources and the improvement of hygiene. We then assist the communities to implement their action plan. The projects are community-led with the community making the decisions. A particular focus is placed on the opinions, experience and expertise of women as they are usually responsible for household water collection, sanitation and hygiene. A water committee is elected to lead the projects, ensure that all community members construct a latrine, that vulnerable households are assisted and that the good practices continue after the projects end. The water pump can be easily maintained with low cost and locally available materials either by the water committee themselves or by the Water Works repair service run by the Water Works Malawian water team.
</p>

<div class="pedestal">
    <video width="700" controls preload="auto">
        <source src="~/videos/ProjectsPageVideo.mp4" type="video/mp4" />
        Your browser does not support the video tag.
    </video>
</div>

<a href="#morevideos">
    <h4 style="text-align:center">More Videos Below</h4>
</a>

<br />

<div class="flex-row">
    <div class="spaced"><img src="~/images/ProjectsPage1.jpg" title="" /></div>
    <div class="spaced"><img src="~/images/ProjectsPage2.jpg" title="" /></div>
</div>

<div class="flex-row">
    <div class="spaced"><img src="~/images/ProjectsPage3.jpg" title="" /></div>
    <div class="spaced"><img src="~/images/ProjectsPage4.jpg" title="" /></div>
</div>

<div class="flex-row">
    <div class="spaced"><img src="~/images/ProjectsPage5.jpg" title="" /></div>
    <div class="spaced"><img src="~/images/ProjectsPage6.jpg" title="" /></div>
</div>

<div class="flex-row">
    <div class="spaced"><img src="~/images/ProjectsPage7.jpg" title="" /></div>
    <div class="spaced"><img src="~/images/ProjectsPage8.jpg" title="" /></div>
</div>

<div class="flex-row">
    <div class="spaced"><img src="~/images/ProjectsPage9.jpg" title="" /></div>
    <div class="spaced"><img src="~/images/ProjectsPage10.jpg" title="" /></div>
</div>

<a name="morevideos">More videos</a>

<br />

<div class="flex-row">
    <div class="spaced">
        <video width="454" controls preload="auto">
            <source src="~/videos/newpumpinKuchata.mp4" />
            Your browser does not support the video tag.
        </video>
        New pump in Kuchata
    </div>

    <div class="spaced">
        <video width="454" controls preload="auto">
            <source src="~/videos/singinganddancing.mp4" type="video/mp4" />
            Your browser does not support the video tag.
        </video>
        Singing and dancing
    </div>
</div>

WaterWorks/WaterWorks/Views/Reports/Index.cshtml
@{
    ViewData["Title"] = "News";
}

<h1 style="text-align:center">Reports</h1>

<br />

<table class="news">
    <tr>
        <td style="width:33%">
            <a href="~/documents/AnnualReportAndFinancialStatement2017-18.pdf"><img src="~/images/AnnualReportAndFinancialStatements2017-18.jpg" alt="Annual Report And Financial Statement 2017-18" class="news" /></a>
            <div>
                <strong>Annual Report 2017-18</strong>
            </div>
        </td>
        <td style="width:33%">
            <a href="~/documents/AnIndependentEvaluationOfWaterWorks2017.pdf"><img src="~/images/AnIndependentEvaluationOfWaterWorks2017.jpg" alt="An Independent Evaluation of Water Works 2017" class="news" /></a>
            <div>
                <strong>Independent Evaluation 2017</strong>
            </div>
        </td>
    </tr>
</table>

WaterWorks/WaterWorks/Views/WaterPumps/Alinafe.cshtml
@{
    ViewData["Title"] = "The Alinafe Pump";
}

<h1>The Alinafe Pump</h1>

<p>
    The Alinafe pump is based on the conventional hand pumps, but is built with low cost materials that can be found at local markets. This means that it is one tenth of the price and is much easier to maintain.
</p>

<p>
    The pumps operates through the principle of suction. The action of moving the handle up causes the water to flow upwards through the rising main and out of the outlet spout. At the bottom of the rising pipe is a valve that allows water to flow upwards but prevents it from flowing back out again. With a short training course communities are easily capable of installing and maintaining the pump.
</p>

<div class="pedestal">
    <img src="~/images/NafeImagesLarge/1.jpg" id="selectedPhoto" class="large-square" />
</div>

<div id="divPhotoGrid" class="gallery">
    <div><img src="~/images/NafeImagesSmall/1.jpg" class="small-square bordered selectable selected" /></div>
    <div><img src="~/images/NafeImagesSmall/2.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/NafeImagesSmall/3.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/NafeImagesSmall/4.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/NafeImagesSmall/5.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/NafeImagesSmall/6.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/NafeImagesSmall/7.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/NafeImagesSmall/8.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/NafeImagesSmall/9.jpg" class="small-square bordered selectable" /></div>
</div>

@section Scripts {
    <script type="text/javascript">
        let selectableElements = document.querySelectorAll('img.selectable');

        selectableElements.forEach(
            item => item.addEventListener('click', (e) => project(selectableElements, e.target, document.querySelector('#selectedPhoto')))
        );
    </script>
}

WaterWorks/WaterWorks/Views/WaterPumps/Index.cshtml
@{
    ViewData["Title"] = "Water Pumps";
}

<p>Over forty percent of the water pumps in Malawi are not working. The maintenance requires specialised knowledge, tools and spare parts, which are often not available within rural communities. We were founded in response to this lack of sustainability and have worked with the University of Edinburgh and local Malawian artisans to develop simple, innovative and sustainable hand pump technologies.</p>
<p>Water Works installed Alinafe Pumps in the past, but currently focuses on using the Rope Pump. Both can be built and maintained by rural communities, using locally available and low cost materials. For more information please click on the photographs.</p>

<div class="pedestal">
    <a asp-area="" asp-controller="WaterPumps" asp-action="Alinafe"><img class="medium-square selectable" src="~/images/WaterPumps/Nafe1.jpg" name="Nafe" id="Nafe" /></a>
    <a asp-area="" asp-controller="WaterPumps" asp-action="RopePump"><img class="medium-square selectable" src="~/images/WaterPumps/RopePump1.jpg" name="RopePump" id="RopePump" /></a>
</div>

<p style="clear:left">&nbsp;</p>

WaterWorks/WaterWorks/Views/WaterPumps/RopePump.cshtml
@{
    ViewData["Title"] = "The Rope Pump";
}

<h1>The Rope Pump</h1>

<p>
    The Rope pump is an example of SMARTech (Simple, Market based, Affordable, Repairable Technology). This is the popular choice for Water Works projects, as it is one-fifth the price of traditional pumps, is simple to install, and the replacement parts are easily found in local markets. The villagers appreciate how easy it is to use and repair.
</p>
<p>
    This pump is made from a bicycle wheel, a plastic pipe and a rope. The principle behind the pump is water lifting. The action of turning the handle pulls a loop of rope around a wheel, through a guide at the bottom of the well and up a plastic pipe (rising pipe) that is submerged under water. The rope has equally spaced circular rubber discs along its length. These discs trap water in the rising pipe and lift it into an outlet spout.
</p>

<div class="pedestal">
    <img src="~/images/RopePumpImagesLarge/1.jpg" id="selectedPhoto" class="large-square" />
</div>

<div id="divPhotoGrid" class="gallery">
    <div><img src="~/images/RopePumpImagesSmall/1.jpg" class="small-square bordered selectable selected" /></div>
    <div><img src="~/images/RopePumpImagesSmall/2.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/RopePumpImagesSmall/3.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/RopePumpImagesSmall/4.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/RopePumpImagesSmall/5.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/RopePumpImagesSmall/6.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/RopePumpImagesSmall/7.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/RopePumpImagesSmall/8.jpg" class="small-square bordered selectable" /></div>
    <div><img src="~/images/RopePumpImagesSmall/9.jpg" class="small-square bordered selectable" /></div>
</div>

@section Scripts {
    <script type="text/javascript">
        let selectableElements = document.querySelectorAll('img.selectable');

        selectableElements.forEach(
            item => item.addEventListener('click', (e) => project(selectableElements, e.target, document.querySelector('#selectedPhoto')))
        );
    </script>
}